#!/bin/bash

# run following command to reset router
# $: ssh admin@router.asus.com <<< "$(cat init_router)"

set -e

if [ ! -d /tmp/mnt/opt/entware.bak ]; then
    echo 'not exist /tmp/mnt/opt/entware.bak, init_router not continuing.'
    exit
fi

[ -e /opt/etc/toggle_proxy.sh ] && sh /opt/etc/toggle_proxy.sh disable

date=$(date '+%Y-%m-%d_%H-%M-%S')
mv /tmp/mnt/opt/entware /tmp/mnt/opt/entware_bak_$date

# recreate a new entware directory.
cp -a /tmp/mnt/opt/entware.bak /tmp/mnt/opt/entware

rm -f /opt/var/lock/opkg.lock

cat <<'HEREDOC' > /jffs/scripts/services-start
#!/bin/sh

RC='/opt/etc/init.d/rc.unslung'

i=30
until [ -x "$RC" ] ; do
  i=$(($i-1))
  if [ "$i" -lt 1 ] ; then
    logger "Could not start Entware"
    exit
  fi
  sleep 1
done
$RC start
HEREDOC

rm -f /jffs/scripts/wan-start /jffs/scripts/dhcpc-event

echo '[0m[33mRouter will reboot ...[0m'
reboot
